# Generated by Django 5.1.2 on 2025-06-24 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_hub', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employees',
            new_name='Employee',
        ),
    ]
